"""Canonical domain event type names.

Names follow the ``<domain>.<action>`` convention agreed for Phase 1. Only
event types that are actually published somewhere in this codebase are
marked ``# published``; the remainder are reserved so future phases can use
a stable, already-agreed vocabulary without inventing new names ad hoc.
Reserving a name here does NOT mean the underlying feature is implemented.
"""

from __future__ import annotations

from enum import StrEnum


class EventType(StrEnum):
    SCENARIO_STARTED = "scenario.started"  # published
    SCENARIO_COMPLETED = "scenario.completed"

    ATTACK_STARTED = "attack.started"
    ATTACK_STEP_EXECUTED = "attack.step.executed"

    TELEMETRY_GENERATED = "telemetry.generated"  # published
    TELEMETRY_RECEIVED = "telemetry.received"

    ANOMALY_DETECTED = "anomaly.detected"  # published

    INCIDENT_CREATED = "incident.created"  # published
    INCIDENT_UPDATED = "incident.updated"
    INCIDENT_CONTAINED = "incident.contained"

    MITRE_OBSERVATION_CREATED = "mitre.observation.created"

    PREDICTION_GENERATED = "prediction.generated"  # published

    RESPONSE_PROPOSED = "response.proposed"  # published
    RESPONSE_APPROVED = "response.approved"  # published
    RESPONSE_REJECTED = "response.rejected"  # published
    RESPONSE_EXECUTION_STARTED = "response.execution.started"  # published
    RESPONSE_EXECUTED = "response.executed"  # published
    RESPONSE_FAILED = "response.failed"  # published

    RESOURCE_STATE_CHANGED = "resource.state.changed"  # published

    VERIFICATION_COMPLETED = "verification.completed"  # published

    ROLLBACK_STARTED = "rollback.started"  # published
    ROLLBACK_COMPLETED = "rollback.completed"  # published

    ATTACK_PATH_DISCOVERED = "attack.path.discovered"  # published
    BLAST_RADIUS_ASSESSED = "blast_radius.assessed"  # published

    RED_STEP_ATTEMPTED = "red.step.attempted"  # published
    RED_STEP_COMPLETED = "red.step.completed"  # published

    PURPLE_EXPERIMENT_STARTED = "purple.experiment.started"  # published
    PURPLE_STEP_COMPLETED = "purple.step.completed"  # published
    PURPLE_EXPERIMENT_COMPLETED = "purple.experiment.completed"  # published

    RESPONSE_PLAN_GENERATED = "response.plan.generated"  # published
    RESPONSE_PLAN_SIMULATED = "response.plan.simulated"  # published
    RESPONSE_PLAN_SELECTED = "response.plan.selected"  # published
    POLICY_EVALUATED = "policy.evaluated"  # published
    AUTONOMY_DECISION = "autonomy.decision"  # published
    APPROVAL_REQUIRED = "approval.required"  # published
    ROLLBACK_TRIGGERED = "rollback.triggered"  # published

    # Phase 5 (Section 101): additive, lightweight lifecycle-correlation
    # events for the reproducible-evaluation engine. These do NOT replace
    # the reconstruction-based Experiment Timeline
    # (`app.services.evaluation.timeline_service`) - that stage's primary
    # source of truth remains the real typed Phase 1-4 records - they exist
    # purely so a live consumer (e.g. a future batch-progress UI) can
    # correlate an experiment/batch's lifecycle milestones via
    # `correlation_id`/`causation_id` without polling the database.
    EVALUATION_BATCH_CREATED = "evaluation.batch.created"  # published
    EVALUATION_EXPERIMENT_STARTED = "evaluation.experiment.started"  # published
    EVALUATION_DEFENCE_COMPLETED = "evaluation.defence.completed"  # published
    EVALUATION_METRICS_COMPUTED = "evaluation.metrics.computed"  # published
    EVALUATION_EXPERIMENT_COMPLETED = "evaluation.experiment.completed"  # published
    EVALUATION_EXPERIMENT_FAILED = "evaluation.experiment.failed"  # published
    # Phase 5 Stage 6: published once an export (CSV or JSON) is actually
    # generated by the Evaluation API - deliberately deferred until this
    # stage, since no export endpoint existed before it.
    EVALUATION_EXPORT_GENERATED = "evaluation.export.generated"  # published
