from __future__ import annotations

from datetime import UTC, datetime

from sqlalchemy.orm import Session

from app.core.exceptions import ApplicationError
from app.database.models import SimulationScenarioRecord
from app.schemas.simulation import ScenarioStep, SimulationScenario
from app.schemas.telemetry import (
    EventAction,
    EventOutcome,
    EventType,
    PrivilegeLevel,
    Severity,
    SourceType,
)


def _step(
    sequence: int,
    offset_seconds: int,
    description: str,
    event_type: EventType,
    action: EventAction,
    outcome: EventOutcome,
    severity: Severity,
    source_type: SourceType,
    source_id: str,
    destination_id: str | None = None,
    user_id: str | None = None,
    device_id: str | None = None,
    privilege_level: PrivilegeLevel | None = None,
    process_name: str | None = None,
    metadata: dict[str, object] | None = None,
) -> ScenarioStep:
    return ScenarioStep(
        sequence=sequence,
        offset_seconds=offset_seconds,
        description=description,
        event_type=event_type,
        action=action,
        outcome=outcome,
        severity=severity,
        source_type=source_type,
        source_id=source_id,
        destination_id=destination_id,
        user_id=user_id,
        device_id=device_id,
        privilege_level=privilege_level,
        process_name=process_name,
        metadata=metadata or {},
    )


SCENARIOS: tuple[SimulationScenario, ...] = (
    SimulationScenario(
        scenario_id="normal-operations",
        name="Steady Cloud Operations",
        description="Routine synthetic office-hours traffic across the simulated cloud estate.",
        steps=[
            _step(
                1,
                0,
                "Normal office-hours API sign-in",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.INFORMATIONAL,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": True, "device_known": True},
            ),
            _step(
                2,
                45,
                "Gateway request forwarded to the load balancer",
                EventType.PORTAL_ACCESS,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.INFORMATIONAL,
                SourceType.SERVICE,
                "api-gateway-01",
                "load-balancer-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.STANDARD,
            ),
            _step(
                3,
                90,
                "Routine application pod request",
                EventType.APPLICATION_REQUEST,
                EventAction.REQUEST,
                EventOutcome.SUCCESS,
                Severity.INFORMATIONAL,
                SourceType.SERVICE,
                "api-gateway-01",
                "application-pod-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.STANDARD,
                "synthetic-gateway-worker",
            ),
            _step(
                4,
                135,
                "Normal cloud database query",
                EventType.DATABASE_QUERY,
                EventAction.QUERY,
                EventOutcome.SUCCESS,
                Severity.LOW,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.SERVICE,
                "synthetic-query-service",
                {"query_category": "customer_summary"},
            ),
            _step(
                5,
                180,
                "Small object storage write",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.LOW,
                SourceType.SERVER,
                "application-pod-01",
                "object-storage-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.STANDARD,
            ),
            _step(
                6,
                240,
                "Normal sign-out",
                EventType.SESSION,
                EventAction.LOGOUT,
                EventOutcome.SUCCESS,
                Severity.INFORMATIONAL,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-user-01",
                "external-user-01",
                PrivilegeLevel.STANDARD,
            ),
        ],
    ),
    SimulationScenario(
        scenario_id="credential-compromise",
        name="Cloud Credential Compromise Exercise",
        description=(
            "Suspicious-looking but entirely synthetic cloud credential and access exercise "
            "telemetry."
        ),
        steps=[
            _step(
                1,
                0,
                "Repeated failed authentication at the API gateway",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": False, "device_known": False},
            ),
            _step(
                2,
                60,
                "Successful login at an unusual hour",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": False, "device_known": False},
            ),
            _step(
                3,
                95,
                "Previously unseen synthetic client observed",
                EventType.SESSION,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"device_known": False, "synthetic_observation": True},
            ),
            _step(
                4,
                145,
                "IAM privilege-level change",
                EventType.PRIVILEGE_CHANGE,
                EventAction.CHANGE_PRIVILEGE,
                EventOutcome.SUCCESS,
                Severity.HIGH,
                SourceType.SERVICE,
                "iam-service-01",
                "external-user-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"previous_privilege": "standard"},
            ),
            _step(
                5,
                195,
                "Access to the application pod",
                EventType.APPLICATION_REQUEST,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "application-pod-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-client",
            ),
            _step(
                6,
                245,
                "Internal connection toward the cloud database",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-db-client",
            ),
            _step(
                7,
                310,
                "Large synthetic outbound transfer",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.HIGH,
                SourceType.DATABASE,
                "cloud-database-01",
                "simulation-egress-sink-01",
                "synthetic-user-01",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-transfer-client",
                {"synthetic_boundary": True, "destination_class": "simulation_sink"},
            ),
        ],
    ),
    SimulationScenario(
        scenario_id="staged-compromise-demo",
        name="Staged Cloud Compromise Demonstration",
        description=(
            "A synthetic visual demonstration with a stable routine period before related "
            "unusual cloud activity."
        ),
        steps=[
            _step(
                1,
                0,
                "Normal office-hours API sign-in",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.INFORMATIONAL,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "external-user-01",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": True, "device_known": True},
            ),
            _step(
                2,
                60,
                "Routine gateway request",
                EventType.PORTAL_ACCESS,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.INFORMATIONAL,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "external-user-01",
                PrivilegeLevel.STANDARD,
            ),
            _step(
                3,
                120,
                "Normal cloud database query",
                EventType.DATABASE_QUERY,
                EventAction.QUERY,
                EventOutcome.SUCCESS,
                Severity.LOW,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-demo-user",
                "external-user-01",
                PrivilegeLevel.SERVICE,
            ),
            _step(
                4,
                180,
                "Small expected object storage write",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.LOW,
                SourceType.SERVER,
                "application-pod-01",
                "object-storage-01",
                "synthetic-demo-user",
                "external-user-01",
                PrivilegeLevel.STANDARD,
                metadata={"channel_type": "expected_internal"},
            ),
            _step(
                5,
                300,
                "Repeated failed authentication attempts",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={
                    "office_hours": False,
                    "device_known": False,
                    "attempt_pattern": "repeated",
                },
            ),
            _step(
                6,
                360,
                "Successful login at an unusual synthetic time",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": False, "device_known": False},
            ),
            _step(
                7,
                410,
                "Previously unseen synthetic client",
                EventType.SESSION,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"device_known": False},
            ),
            _step(
                8,
                465,
                "Explicit IAM permission change",
                EventType.PRIVILEGE_CHANGE,
                EventAction.CHANGE_PRIVILEGE,
                EventOutcome.SUCCESS,
                Severity.HIGH,
                SourceType.SERVICE,
                "iam-service-01",
                "external-user-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"account_manipulation": True, "previous_privilege": "standard"},
            ),
            _step(
                9,
                525,
                "Remote service access toward the application pod",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.DEVICE,
                "external-user-01",
                "application-pod-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"remote_service": "synthetic-cloud-shell"},
            ),
            _step(
                10,
                585,
                "Connection toward the cloud database",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"remote_service": "synthetic-database-service"},
            ),
            _step(
                11,
                660,
                "Large outbound transfer to documentation sink",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.HIGH,
                SourceType.DATABASE,
                "cloud-database-01",
                "simulation-egress-sink-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={
                    "synthetic_boundary": True,
                    "channel_type": "synthetic_web_service",
                    "web_service": "demo-upload-service",
                },
            ),
            _step(
                12,
                720,
                "Final synthetic session observation",
                EventType.SESSION,
                EventAction.LOGOUT,
                EventOutcome.SUCCESS,
                Severity.LOW,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-demo-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
            ),
        ],
    ),
    SimulationScenario(
        scenario_id="leaked-api-credential",
        name="Red Agent · Leaked API Credential",
        description=(
            "Deterministic Red Agent scenario in which a leaked synthetic API credential is "
            "replayed against the gateway, escalated through IAM and used to stage a bulk export."
        ),
        steps=[
            _step(
                1,
                0,
                "Leaked API key replayed with repeated authentication failures",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={
                    "office_hours": False,
                    "device_known": False,
                    "attempt_pattern": "repeated",
                    "credential_source": "synthetic_leaked_api_key",
                },
            ),
            _step(
                2,
                45,
                "Leaked credential authenticates successfully",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={"office_hours": False, "device_known": False},
            ),
            _step(
                3,
                95,
                "Over-scoped token request against the IAM service",
                EventType.APPLICATION_REQUEST,
                EventAction.REQUEST,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "api-gateway-01",
                "iam-service-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-token-broker",
                {"api_key_scope": "over_privileged"},
            ),
            _step(
                4,
                150,
                "IAM role binding is modified for the synthetic service account",
                EventType.PRIVILEGE_CHANGE,
                EventAction.CHANGE_PRIVILEGE,
                EventOutcome.SUCCESS,
                Severity.HIGH,
                SourceType.SERVICE,
                "iam-service-01",
                "auth-pod-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"account_manipulation": True, "previous_privilege": "service"},
            ),
            _step(
                5,
                205,
                "Elevated credential reaches the application pod",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVICE,
                "api-gateway-01",
                "application-pod-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"remote_service": "synthetic-cloud-api"},
            ),
            _step(
                6,
                260,
                "Bulk record query against the cloud database",
                EventType.DATABASE_QUERY,
                EventAction.QUERY,
                EventOutcome.SUCCESS,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-export-worker",
                {"query_category": "bulk_export"},
            ),
            _step(
                7,
                320,
                "Large export staged into synthetic object storage",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "object-storage-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-transfer-client",
                {
                    "channel_type": "synthetic_web_service",
                    "web_service": "synthetic-object-export",
                },
            ),
            _step(
                8,
                380,
                "Synthetic session closed",
                EventType.SESSION,
                EventAction.LOGOUT,
                EventOutcome.SUCCESS,
                Severity.LOW,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-service-account",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
            ),
        ],
    ),
    SimulationScenario(
        scenario_id="suspicious-kubernetes-pod",
        name="Red Agent · Suspicious Kubernetes Pod",
        description=(
            "Deterministic Red Agent scenario in which an unverified synthetic pod image is "
            "scheduled onto a worker node and reaches for identity and data services."
        ),
        steps=[
            _step(
                1,
                0,
                "Unverified synthetic pod image submitted to the control plane",
                EventType.APPLICATION_REQUEST,
                EventAction.REQUEST,
                EventOutcome.SUCCESS,
                Severity.LOW,
                SourceType.SERVICE,
                "admin-service-01",
                "kubernetes-cluster-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ADMINISTRATOR,
                "synthetic-deploy-agent",
                {
                    "workload_change": "pod_created",
                    "pod_image": "synthetic-unverified-image",
                    "image_signature_verified": False,
                },
            ),
            _step(
                2,
                60,
                "Control plane schedules the pod onto the worker node",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "kubernetes-cluster-01",
                "worker-node-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-scheduler",
                {"pod_name": "synthetic-suspicious-pod"},
            ),
            _step(
                3,
                120,
                "Pod requests host-level access on the worker node",
                EventType.SESSION,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "worker-node-01",
                "application-pod-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-container-runtime",
                {"privileged_container": True, "device_known": False},
            ),
            _step(
                4,
                180,
                "Repeated service-token failures against the IAM service",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "application-pod-01",
                "iam-service-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                metadata={"attempt_pattern": "repeated", "office_hours": False},
            ),
            _step(
                5,
                240,
                "Service token is accepted after repeated failures",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.SUCCESS,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "application-pod-01",
                "iam-service-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                metadata={"office_hours": False, "device_known": False},
            ),
            _step(
                6,
                300,
                "Pod service account is granted elevated permissions",
                EventType.PRIVILEGE_CHANGE,
                EventAction.CHANGE_PRIVILEGE,
                EventOutcome.SUCCESS,
                Severity.HIGH,
                SourceType.SERVICE,
                "iam-service-01",
                "application-pod-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"account_manipulation": True, "previous_privilege": "service"},
            ),
            _step(
                7,
                360,
                "Pod opens a remote execution channel toward the cloud database",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                metadata={"remote_service": "synthetic-pod-exec"},
            ),
            _step(
                8,
                430,
                "Records copied over a synthetic sidecar channel",
                EventType.DATA_TRANSFER,
                EventAction.TRANSFER,
                EventOutcome.COMPLETED,
                Severity.HIGH,
                SourceType.DATABASE,
                "cloud-database-01",
                "object-storage-01",
                "synthetic-pipeline-user",
                "synthetic-unseen-device",
                PrivilegeLevel.ELEVATED,
                "synthetic-sidecar",
                {"channel_type": "synthetic_c2", "c2_channel": "synthetic-sidecar"},
            ),
        ],
    ),
    SimulationScenario(
        scenario_id="ddos-traffic-spike",
        name="Red Agent · DDoS-like Traffic Spike",
        description=(
            "Deterministic Red Agent scenario in which synthetic request volume saturates the "
            "gateway and load balancer and degrades downstream cloud services."
        ),
        steps=[
            _step(
                1,
                0,
                "Baseline request rate at the API gateway",
                EventType.PORTAL_ACCESS,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.INFORMATIONAL,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-anonymous-client",
                "external-user-01",
                PrivilegeLevel.STANDARD,
                metadata={"request_rate_per_second": 40, "traffic_profile": "baseline"},
            ),
            _step(
                2,
                30,
                "Request volume rises far above the learned baseline",
                EventType.PORTAL_ACCESS,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={
                    "request_rate_per_second": 5200,
                    "traffic_profile": "spike",
                    "device_known": False,
                    "office_hours": False,
                },
            ),
            _step(
                3,
                60,
                "Load balancer connection pool saturates",
                EventType.APPLICATION_REQUEST,
                EventAction.REQUEST,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.SERVICE,
                "api-gateway-01",
                "load-balancer-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-gateway-worker",
                {"saturation": "connection_pool", "error_rate": 0.34},
            ),
            _step(
                4,
                90,
                "Repeated authentication failures inside the traffic flood",
                EventType.AUTHENTICATION,
                EventAction.LOGIN,
                EventOutcome.FAILURE,
                Severity.MEDIUM,
                SourceType.DEVICE,
                "external-user-01",
                "api-gateway-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.STANDARD,
                metadata={
                    "attempt_pattern": "repeated",
                    "office_hours": False,
                    "device_known": False,
                },
            ),
            _step(
                5,
                120,
                "Cluster scales out under sustained synthetic load",
                EventType.INTERNAL_CONNECTION,
                EventAction.CONNECT,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVICE,
                "load-balancer-01",
                "kubernetes-cluster-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-autoscaler",
                {"autoscale_event": "synthetic_scale_out", "pending_pods": 6},
            ),
            _step(
                6,
                150,
                "Application pod is evicted from the worker node",
                EventType.APPLICATION_REQUEST,
                EventAction.REQUEST,
                EventOutcome.FAILURE,
                Severity.HIGH,
                SourceType.SERVICE,
                "worker-node-01",
                "application-pod-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-kubelet",
                {"pod_state": "synthetic_evicted", "cpu_saturation": 0.97},
            ),
            _step(
                7,
                190,
                "Cloud database connections time out",
                EventType.DATABASE_QUERY,
                EventAction.QUERY,
                EventOutcome.FAILURE,
                Severity.HIGH,
                SourceType.SERVER,
                "application-pod-01",
                "cloud-database-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-query-service",
                {"connection_timeouts": 118},
            ),
            _step(
                8,
                240,
                "Monitoring records a synthetic availability breach",
                EventType.SESSION,
                EventAction.ACCESS,
                EventOutcome.ALLOWED,
                Severity.HIGH,
                SourceType.SERVICE,
                "monitoring-service-01",
                "kubernetes-cluster-01",
                "synthetic-anonymous-client",
                "synthetic-unseen-device",
                PrivilegeLevel.SERVICE,
                "synthetic-sla-monitor",
                {"availability_breach": True, "sla_state": "degraded"},
            ),
        ],
    ),
)

RED_AGENT_SCENARIO_IDS = (
    "leaked-api-credential",
    "suspicious-kubernetes-pod",
    "ddos-traffic-spike",
)


class ScenarioService:
    def __init__(self) -> None:
        self._definitions = {scenario.scenario_id: scenario for scenario in SCENARIOS}

    def ensure_persisted(self, session: Session) -> None:
        for scenario in SCENARIOS:
            if session.get(SimulationScenarioRecord, scenario.scenario_id) is None:
                session.add(
                    SimulationScenarioRecord(
                        scenario_id=scenario.scenario_id,
                        name=scenario.name,
                        description=scenario.description,
                        steps=[step.model_dump(mode="json") for step in scenario.steps],
                        synthetic=True,
                        created_at=datetime(2026, 7, 21, tzinfo=UTC),
                    )
                )
        session.flush()

    def list_scenarios(self, session: Session) -> list[SimulationScenario]:
        self.ensure_persisted(session)
        return list(SCENARIOS)

    def get_scenario(self, session: Session, scenario_id: str) -> SimulationScenario:
        self.ensure_persisted(session)
        scenario = self._definitions.get(scenario_id)
        if scenario is None:
            raise ApplicationError(
                "SCENARIO_NOT_FOUND", "The requested simulation scenario was not found.", 404
            )
        return scenario


scenario_service = ScenarioService()
