"""Add simulation-only response orchestration and audit persistence."""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = "20260722_0008"
down_revision: Union[str, None] = "20260722_0007"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def synthetic() -> sa.Column[bool]:
    return sa.Column("synthetic", sa.Boolean(), nullable=False)


def upgrade() -> None:
    op.create_table("response_orchestrations", sa.Column("orchestration_id", sa.String(36), primary_key=True), sa.Column("simulation_run_id", sa.String(36), nullable=False), sa.Column("model_id", sa.String(36), nullable=False), sa.Column("incident_candidate_id", sa.String(36), nullable=False), sa.Column("through_sequence_number", sa.Integer(), nullable=False), sa.Column("orchestration_version", sa.String(40), nullable=False), sa.Column("current_state", sa.String(60), nullable=False), sa.Column("selected_recommendation_id", sa.String(36), nullable=False), sa.Column("required_approval_tier", sa.String(40), nullable=False), sa.Column("created_by", sa.String(100), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), synthetic(), sa.UniqueConstraint("simulation_run_id", "model_id", "incident_candidate_id", "selected_recommendation_id", "through_sequence_number", name="uq_response_orchestration_input"))
    op.create_table("response_plan_steps", sa.Column("plan_step_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("step_number", sa.Integer(), nullable=False), sa.Column("playbook_id", sa.String(80), nullable=False), sa.Column("recommendation_id", sa.String(36), nullable=False), sa.Column("target_type", sa.String(30), nullable=False), sa.Column("target_id", sa.String(220), nullable=False), sa.Column("required_approval_tier", sa.String(40), nullable=False), sa.Column("reversibility", sa.String(30), nullable=False), sa.Column("rationale", sa.String(1000), nullable=False), sa.Column("expected_mutation_json", sa.JSON(), nullable=False), sa.Column("current_status", sa.String(50), nullable=False), synthetic(), sa.UniqueConstraint("orchestration_id", "step_number", name="uq_plan_step"))
    op.create_table("agent_decisions", sa.Column("agent_decision_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("agent_name", sa.String(80), nullable=False), sa.Column("agent_version", sa.String(40), nullable=False), sa.Column("decision_type", sa.String(80), nullable=False), sa.Column("input_reference_ids_json", sa.JSON(), nullable=False), sa.Column("output_summary", sa.String(1000), nullable=False), sa.Column("decision", sa.String(80), nullable=False), sa.Column("ranking_score", sa.Float()), sa.Column("rationale", sa.String(1000), nullable=False), sa.Column("warnings_json", sa.JSON(), nullable=False), sa.Column("next_agent", sa.String(80)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), synthetic())
    op.create_table("approval_requests", sa.Column("approval_request_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("plan_step_id", sa.String(36)), sa.Column("required_role", sa.String(30), nullable=False), sa.Column("approval_state", sa.String(30), nullable=False), sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True)), sa.Column("decided_at", sa.DateTime(timezone=True)), sa.Column("decided_by", sa.String(120)), sa.Column("decision_reason", sa.String(1000)), synthetic())
    op.create_table("synthetic_executions", sa.Column("execution_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("plan_step_id", sa.String(36), nullable=False), sa.Column("playbook_id", sa.String(80), nullable=False), sa.Column("target_type", sa.String(30), nullable=False), sa.Column("target_id", sa.String(220), nullable=False), sa.Column("execution_state", sa.String(40), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("mutation_summary_json", sa.JSON(), nullable=False), sa.Column("changed_node_ids_json", sa.JSON(), nullable=False), sa.Column("changed_edge_ids_json", sa.JSON(), nullable=False), sa.Column("pre_execution_state_reference", sa.String(80), nullable=False), sa.Column("post_execution_state_reference", sa.String(80)), sa.Column("simulated_failure_reason", sa.String(300)), sa.Column("reversible", sa.Boolean(), nullable=False), synthetic(), sa.UniqueConstraint("orchestration_id", "plan_step_id", name="uq_execution_step"))
    op.create_table("response_verifications", sa.Column("verification_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("execution_id", sa.String(36), nullable=False, unique=True), sa.Column("verification_status", sa.String(50), nullable=False), sa.Column("metrics_json", sa.JSON(), nullable=False), sa.Column("unintended_effects_json", sa.JSON(), nullable=False), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False), synthetic())
    op.create_table("rollback_records", sa.Column("rollback_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False, unique=True), sa.Column("execution_id", sa.String(36), nullable=False), sa.Column("reason", sa.String(1000), nullable=False), sa.Column("requested_by", sa.String(120), nullable=False), sa.Column("approval_request_id", sa.String(36)), sa.Column("state", sa.String(50), nullable=False), sa.Column("restored_state_reference", sa.String(80)), sa.Column("started_at", sa.DateTime(timezone=True), nullable=False), sa.Column("completed_at", sa.DateTime(timezone=True)), sa.Column("verification_summary_json", sa.JSON(), nullable=False), synthetic())
    op.create_table("audit_events", sa.Column("audit_event_id", sa.String(36), primary_key=True), sa.Column("orchestration_id", sa.String(36), nullable=False), sa.Column("sequence_number", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("actor_type", sa.String(30), nullable=False), sa.Column("actor_id", sa.String(100), nullable=False), sa.Column("actor_display_name", sa.String(120), nullable=False), sa.Column("previous_event_hash", sa.String(64), nullable=False), sa.Column("event_hash", sa.String(64), nullable=False), sa.Column("canonical_payload_json", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), synthetic(), sa.UniqueConstraint("orchestration_id", "sequence_number", name="uq_audit_sequence"))


def downgrade() -> None:
    for table in ["audit_events", "rollback_records", "response_verifications", "synthetic_executions", "approval_requests", "agent_decisions", "response_plan_steps", "response_orchestrations"]:
        op.drop_table(table)
