from typing import Any

class Pipeline:
    def __init__(self, steps: list[tuple[str, object]]) -> None: ...
    def fit(self, values: object) -> Pipeline: ...
    def decision_function(self, values: object) -> Any: ...
